config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :spots, except: [:index] do
    resources :reviews do
      member do
        put "like",    to: "reviews#upvote"
        put "dislike", to: "reviews#downvote"
      end
    end
  end
  resource :user_session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :destroy] do
    resources :spots, only: [:index, :show]
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
	acts_as_votable
	belongs_to :author, class_name: "User"
	belongs_to :spot, class_name: "Spot"

	validates :author, presence: true

	self.per_page = 1

	default_scope -> {order(:cached_weighted_average => :desc)}
end

app/models/spot.rb
class Spot < ActiveRecord::Base
	belongs_to :author, class_name: "User"

	has_many :reviews, dependent: :destroy
	accepts_nested_attributes_for :reviews

	validates :author, :name, :img_url, :address, :phone, :category, presence: true

	self.per_page = 10

	filterrific(
	  default_filter_params: { sorted_by: 'created_at_desc' },
	  available_filters: [
		:sorted_by,
		:search_query
	  ]
	)

	scope :search_query, lambda { |query|
	  return nil  if query.blank?
	  terms = query.downcase.split(/\s+.*/)
	  terms = terms.map { |e|
		(e.gsub('*', '%') + '%').gsub(/%+/, '%')
	  }
	  num_or_conditions = 4
	  where(
		terms.map {
		  or_clauses = [
			"LOWER(spots.name) LIKE ?",
			"LOWER(spots.category) LIKE ?",
			"LOWER(spots.address) LIKE ?",
			"LOWER(spots.phone) LIKE ?"
		  ].join(' OR ')
		  "(#{ or_clauses })"
		}.join(' AND '),
		*terms.map { |e| [e] * num_or_conditions }.flatten
	  )
	}

	# scope :with_category, lambda { |categories|
	# 	where(category: [*categories])
	# }

	scope :sorted_by, lambda { |sort_option|
	  # extract the sort direction from the param value.
	  direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
	  case sort_option.to_s
	  when /^created_at_/
	    order("spots.created_at #{ direction }")
	  when /^name_/
	    # Simple sort on the name colums
	    order("LOWER(spots.name) #{ direction }")
	  else
	    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
	  end
	}


	/def self.options_for_with_category
	    [
	      ['Name (a-z)', 'name_asc'],
	      ['Registration date (newest first)', 'created_at_desc'],
	      ['Registration date (oldest first)', 'created_at_asc'],
	      ['Spot (a-z)', 'spot_name_asc']
	    ]
	end/

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :spots, foreign_key: :author_id

  validates :email, :name, presence: true
  validates :name, length: { minimum: 3 }
  validates :email, format: { with: /.+@.+\..+/, message: "must be an email address" }, uniqueness: true
  validates :password, confirmation: true
  validates :password, :password_confirmation, presence: { on: :create }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def not_authenticated
    redirect_to root_path, alert: "You do not have permission to access that page."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@filterrific = initialize_filterrific(
		  Spot,
		  params[:filterrific]
		) or return
		@spots = @filterrific.find.page(params[:page])
		@user = current_user if current_user
		respond_to do |format|
		  format.html
		  format.js
		end
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # def index
  #   @reviews = Review.all
  # end

  # def new
  #   @review = Review.new
  #   puts params.to_s
  #   @spot = Spot.find(params[:spot_id])
  #   @thegood = @spot.reviews.build(kind: "The Good")
  #   @thebad= @spot.reviews.build(kind: "The Bad")
  #   @theugly= @spot.reviews.build(kind: "The Ugly")
  # end


  def create
    @spot = Spot.find(params[:spot_id])
    params[:reviews].each do |review_params|
      review_params = review_params.permit(:content, :kind)
      review = @spot.reviews.build(review_params)
      review.author=current_user
      review.save
    end
    if @spot.save
      redirect_to :back, notice: "You have added your review!"
    else
      flash.alert = "We couldn't add your review!. Please correct the errors below."
      render :new
    end
  end

  def upvote
    @review = Review.find(params[:id])
    @review.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @review = Review.find(params[:id])
    @review.downvote_by current_user
    redirect_to :back
  end

  def review_params
    params.require(:review).permit(:content, :kind)
  end


end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_filter :load_user, except: [:new, :create]
  before_action :require_login, except: [:index, :show]

  def new
    @spot = Spot.new
    @thegood = @spot.reviews.build(kind: "The Good")
    @thebad= @spot.reviews.build(kind: "The Bad")
    @theugly= @spot.reviews.build(kind: "The Ugly")
  end


  def create
    @spot = Spot.new
    @spot.assign_attributes(spot_params)
    @spot.author = current_user
    @spot.reviews.each do |review|
      review.author=current_user
    end
    # binding.pry
    if @spot.save
      redirect_to root_path, notice: "You have added #{Spot.name}!"
    else
      flash.alert = "We couldn't add your spot!. Please correct the errors below."
      render :new
    end
  end

  def show
    @spot = Spot.find(params[:id])
    @thegood = @spot.reviews.build(kind: "The Good")
    @thebad= @spot.reviews.build(kind: "The Bad")
    @theugly= @spot.reviews.build(kind: "The Ugly")
    @reviews = [@thegood, @thebad, @theugly]
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to root_path
  end

  private

  def load_spot
    if params[:id].present?
      @spot = Spot.find(params[:id])
    else
      @spot = Spot.new
    end

    if params[:spot].present?
      @spot.assign_attributes(spot_params)
    end
  end

  def load_user
    @user = current_user
  end

  def spot_params
    params.require(:spot).permit(:author, :name, :img_url, :address, :phone, :category, reviews_attributes: [:content, :kind])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:user][:email], params[:user][:password])
      redirect_to root_path, notice: "Welcome back, #{@user.name}"
    else
      @user = User.new(email: params[:user][:email])
      flash.alert = "We could not sign you in. Please check your email/password and try again."
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: "You have been signed out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, notice: "Welcome, #{@user.name}"
    else
      flash.alert = "Please fix the errors below to continue."
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_list.html.haml
%d#filterrific_results
  %div
  %table(class="table table-hover")
    %tr
      %th Name
      %th Category
      %th Added By
      %th
    - @spots.each do |spot|
      %tr
        %td=link_to spot.name, spot_path(spot.id)
        %td= spot.category
        %td= spot.author.name
        - if @user && spot.author_id == @user.id
          %td(type="submit" class="btn btn-primary delete")=link_to "X", spot_path(spot), method: :delete
        - else
          %td
  %div(class="container")
    %div(class="row")
      %div(div class="col-md-2")
      %div(div class="col-md-8")
        = will_paginate spots
      %div(div class="col-md-2")

app/views/home/index.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title The Ugly
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body(id="home_page")
    %div(class="subheader_div")
      %h1(class="main_h1") The Ugly.
      %h2(class="main_h2") everything you really need to know about your favorite local spots.
    %div(class="container")
      %div(class="row")
        %div(div class="col-md-1")
        %div(div class="col-md-10")
          %h1(class = "spots_header") Spots
          = form_for_filterrific @filterrific do |f|
            .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Search by first name, last name, or email.' }
              %label Search
              = f.text_field :search_query, :class => "filterrific-periodically-observed form-control"
              / %label Category
              / = f.select( :with_category, @filterrific.select_options[:with_category], { include_blank: '- Any -' } )

            //%div
            // Sorted by
            //  = f.select(:sorted_by, @filterrific.select_options[:sorted_by])

            %div
              / = link_to "Reset filters", reset_filterrific_url

              = render_filterrific_spinner
            %div
              = render(partial: 'home/list',locals: { spots: @spots })
        %div(div class="col-md-1")











      / %p everything you really need to know about your favorite local spots.
      / %h2
      /   - @spots.each do |spot|
      /     %img(src="#{spot.img_url}")
      /     = spot.name
      /     = spot.category

app/views/home/index.js.haml
- js = escape_javascript(
- render(partial: 'spots/list', locals: { spots: @spots })
- )
$("#filterrific_results").html("#{js}");

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title The Ugly
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      %nav(class='navbar navbar-inverse navbar-fixed-top')
        %div(class='container-fluid navbar-left')
          %div(class='navbar-header')
            %button(type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='navbar-collapse-1' aria-expanded='false')
              %span(class='sr-only') Toggle Navigation
              %span(class='icon-bar')
              %span(class='icon-bar')
              %span(class='icon-bar')
            %a(class='navbar-brand')

        %div(class='collapse navbar-collapse navbar-right' id='navbar-collapse-1')
          %ul(class='nav navbar-nav')
            - if !logged_in?
              - unless controller_name == "users"
                %li= link_to "Sign Up", new_user_path
              - unless controller_name == 'user_sessions'
                %li= link_to "Sign In", new_user_session_path
            - else
              %li= link_to "Phone Home", root_path
              %li= link_to "Add a Spot!", new_spot_path
              %li= link_to "Sign Out", user_session_path, method: :delete
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/reviews/new.html.haml
%div(class="spot_page_add_new_review")
  %div(class="container add_review_page_container")
    %div(class="row")
      %div(div class="col-md-12 add_new_review_content")
          = simple_form_for @spot do |f|
          = f.simple_fields_for :reviews do |g|
            %p="#{g.object.kind}"
            =g.input :content
            =g.input :kind, as: :hidden
          = f.button :submit, "Add your spot!", class: "btn btn-primary"

app/views/spots/new.html.haml
%div(class="spot_page_add_new")
  %div(class="container spot_page_container")
    %div(class="row")
      %div(div class="col-md-4")
      %div(div class="col-md-4")
        = simple_form_for @spot do |f|
          %h3 Name
          = f.input :name
          %h3 Image URL
          = f.input :img_url
          %h3 Address
          = f.input :address
          %h3 Phone Number
          = f.input :phone
          %h3 Category
          = f.select :category, ["Bar/Restaurant", "Entertainment", "Other"],input_html: {:class => "btn btn-primary dropdown-toggle"}
          = f.simple_fields_for :reviews do |g|
            %p="#{g.object.kind}"
            =g.input :content
            =g.input :kind, as: :hidden
          = f.button :submit, "Add your spot!"
      %div(div class="col-md-4")



      / accepts_nested_attributes_for :reviews

app/views/spots/show.html.haml
%div(class="container spot_page_main")
  %div(class="row")
    %div(div class="col-md-12")
      %h1(class="spot_page_head")=@spot.name
  %div(class="row ")
    %div(div class="col-md-5")
      %img(src="#{@spot.img_url}")
    %div(div class="col-md-4 spot_info")
      %p=fa_icon "building"
      %a{:href => "https://www.google.com/#q=#{@spot.address}", :target => "_blank"}=@spot.address
      %p=fa_icon "phone-square"
      %p=@spot.phone
    %div(div class="col-md-3 spot_info")
      %p=fa_icon "bookmark-o"
      %p=@spot.category
      %p(class="user_fa")=fa_icon "user"
      %p=@spot.author.name
      / %a{:href => "https://www.google.com/#q=#{@spot.name}+nashville", :target => "_blank"}=fa_icon "google"
  %div(class="row good_bad_ug")
    %div(div class="col-md-4")
      %h1 The Good
    %div(div class="col-md-4")
      %h1 The Bad
    %div(div class="col-md-4")
      %h1 The Ugly
  %div(class="row good_bad_ug_com")
    %div(div class="col-md-4 review")
      - @spot.reviews.where(kind:"The Good").each do |review|
        %p= review.content
        = link_to like_spot_review_path(review.spot_id, review.id), method: :put, class: "btn btn-default btn-sm" do
          %span(class="glyphicon glyphicon-chevron-up")
          =review.get_upvotes.size
        = link_to dislike_spot_review_path(review.spot_id, review.id), method: :put, class: "btn btn-default btn-sm" do
          %span(class="glyphicon glyphicon-chevron-down")
          =review.get_downvotes.size
    %div(div class="col-md-4 review")
      - @spot.reviews.where(kind:"The Bad").each do |review|
        %p= review.content if review.content != nil
        = link_to like_spot_review_path(review.spot_id, review.id), method: :put, class: "btn btn-default btn-sm" do
          %span(class="glyphicon glyphicon-chevron-up")
          =review.get_upvotes.size
        = link_to dislike_spot_review_path(review.spot_id, review.id), method: :put, class: "btn btn-default btn-sm" do
          %span(class="glyphicon glyphicon-chevron-down")
          =review.get_downvotes.size
    %div(div class="col-md-4 review")
      - @spot.reviews.where(kind:"The Ugly").each do |review|
        %p= review.content if review.content != nil
        = link_to like_spot_review_path(review.spot_id, review.id), method: :put, class: "btn btn-default btn-sm" do
          %span(class="glyphicon glyphicon-chevron-up")
          =review.get_upvotes.size
        = link_to dislike_spot_review_path(review.spot_id, review.id), method: :put, class: "btn btn-default btn-sm" do
          %span(class="glyphicon glyphicon-chevron-down")
          =review.get_downvotes.size

%div(class="row_review")
  %div(class="container")
    %div(class="row")
      .col-md-12
      - if logged_in?
        %h2(class="add_review_header") Go Ahead, Gimme the good, the bad, and the ugly.
        = form_tag spot_reviews_path(@spot), method: :post do
          - @reviews.each do |review|
            = fields_for "reviews[]", review do |x|
              = x.hidden_field :kind
              = x.text_area :content
          = submit_tag

app/views/user_sessions/new.html.haml
%div(class="spot_page_signin")
  %div(class="container spot_page_signin")
    %div(class="row")
      %div(div class="col-md-4")
      %div(div class="col-md-4")
        %h1(class="sign_in_header") Welcome Back!
        = simple_form_for @user, url: user_session_path do |f|
          %h3 Email
          = f.input :email
          %h3 Password
          = f.input :password
          = f.button :submit, "Sign In"
      %div(div class="col-md-4")

app/views/users/new.html.haml
%div(class= "sign_up_page")
  %div(class="container spot_page_signup")
    %div(class="row")
      %div(div class="col-md-4")
      %div(div class="col-md-4 sign_up_content")
        %h1(class="sign_up_label") Hey, we'd love to have you!

        = simple_form_for @user do |f|
          %h3 Username
          = f.input :name
          %h3 Email Address
          = f.input :email
          %h3 Password
          = f.input :password
          %h3 Confirm Passowrd
          = f.input :password_confirmation
          = f.button :submit, "Sign Up"
      %div(div class="col-md-4")